[build]
publish = "public" 
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "https://master--kqh.netlify.com/*"
to = "https://kqh.me/:splat"
status = 301
force = true
[[redirects]]
from = "https://master.kqh.netlify.com/*"
to = "https://kqh.me/:splat"
status = 301
force = true
[[redirects]]
from = "https://kqh.netlify.com/*"
to = "https://kqh.me/:splat"
status = 301
force = true
